deploy_mirror:
  stage: deploy
  script:
    - TMP_DIR=$(mktemp -d)
    - cp -r ./* "$TMP_DIR"/
    - cd "$TMP_DIR"
    - git init
    - git remote add origin https://$GH_USER:$GH_TOKEN@github.com/$GH_USER/$GH_REPO.git
    - git config user.name "$GH_USER"
    - git config user.email "$GH_USER@users.noreply.github.com"
    - git add .
    - git commit --allow-empty -m "Mirror"
    - git branch -M master
    - git push --force origin master
  only:
    - master
