services:
  api:
    build: ./api
    container_name: murky_api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    environment:
      ALLOWED_ORIGINS: http://localhost:5137;http://localhost:8081
#  dash:
#    image: node:24
#    container_name: murky_dash_react
#    working_dir: /app
#    volumes:
#      - ./dash_react:/app
#    ports:
#      - "5137:5137"
#    command: npm run dev -- --host 0.0.0.0 --port 5137
#    environment:
#      VITE_API_URL: http://localhost:8080
  dash:
    image: node:24
    container_name: murky_dash_mithril
    working_dir: /app
    volumes:
      - ./dash_mithril:/app
    ports:
      - "5137:5137"
    command: npm run dev -- --host 0.0.0.0 --port 5137
    environment:
      VITE_API_URL: http://localhost:8080