services:
  api:
    build:
      context: ./api
      target: dev
    container_name: murky_api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./api/tmp/db_backups:/db_backups
    env_file:
      - ./api/.env
      - ./api/.env.local
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: murky_redis
  dash:
    image: node:24
    container_name: murky_dash
    working_dir: /app
    volumes:
      - ./dash:/app
    ports:
      - "5137:5137"
    command: npm run dev -- --host 0.0.0.0 --port 5137
    env_file:
      - ./dash/.env
      - ./dash/.env.local
